[config1]
COORDINATOR_API_KEY='sk-027d41a948474d789f10658a3456cd8c'
COORDINATOR_MODEL='deepseek/deepseek-chat'
COORDINATOR_BASE_URL=''


MODELER_API_KEY='sk-027d41a948474d789f10658a3456cd8c'
MODELER_MODEL='deepseek/deepseek-chat'
MODELER_BASE_URL=''

CODER_API_KEY='sk-027d41a948474d789f10658a3456cd8c'
CODER_MODEL='deepseek/deepseek-chat'
CODER_BASE_URL=''

WRITER_API_KEY='sk-027d41a948474d789f10658a3456cd8c'
WRITER_MODEL='deepseek/deepseek-chat'
WRITER_BASE_URL=''

[config2]


[current]
current = 'config1'
